data_config:
  train_date: '2018-01-01'
  reg_target_name: days_to_pay
  row_id_cols:
    - supplier_number
    - unique_invoice_id
    - unique_payer_id
  features_cols:
    - invoice_amt
    - payer_prev_days_to_pay
    - avg_payer_prev_days_to_pay
    - std_payer_prev_days_to_pay
    - payer_outstanding_invoices
    - payer_outstanding_dollars
    - vendor_prev_days_to_pay
    - avg_vendor_prev_days_to_pay
    - std_vendor_prev_days_to_pay
    - vendor_outstanding_invoices
    - vendor_outstanding_dollars
    - invoice_month
    - invoice_dayofweek
    - is_us_holiday

model_config:
  days_of_week_order:
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    - Sunday
  cat_features:
    - invoice_month
    - invoice_dayofweek
    - is_us_holiday
  cat_features_to_encode:
    - invoice_dayofweek
  quantiles:
    - 0.05
    - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
    - 0.95

params:
  loss: quantile
  max_iter: 100
  learning_rate: 0.05
  max_leaf_nodes: 20
  l2_regularization: 0.1
  random_state: 42
  categorical_features:
    - invoice_month
    - invoice_dayofweek
    - is_us_holiday
